# Start from the ubuntu image that is smaller but no fancy tools
FROM ubuntu:22.04

# Use /usr/src/app as our workdir. The following instructions will be executed in this location.
WORKDIR /usr/src/app

# Copy the hello.sh file from this directory to /usr/src/app/ creating /usr/src/app/hello.sh
COPY script.sh .

RUN apt-get update && apt-get -y install curl

# When running docker run the command will be ./hello.sh
CMD ./script.sh
